spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mallcloud?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.mallplus.common.model
  global-config:
    db-config:
      id-type: ID_WORKER_STR
moke:
  elasticsearch:
    hostlist: ${eshostlist:127.0.0.1:9200} #多个结点中间用逗号分隔
  course:
    index: moke-course
    type: doc
    source_field: id,name,grade,mt,st,charge,valid,pic,qq,price,price_old,status,studymodel,teachmode,expires,pub_time,start_time,end_time
  media:
    index: moke_course_media
    type: doc
    source_field: courseid,media_id,media_url,teachplan_id,media_fileoriginalname

mall:
  swagger:
    enabled: true
    title: 用户中心
    description: 用户中心接口文档
    version: 1.0
    base-package: com.moke.search.controller
  cache-manager:
    configs:
      - key: menu
        second: 600
      - key: user
        second: 1800

