spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mallcloud?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.moke.common.model
  global-config:
    db-config:
      id-type: ID_WORKER_STR
wechat:
  appId: wx5eb8d115be25bb96
  grantType: authorization_code
  secret: b12bbe8bb346f7c484f6b0eae7c64eec
  sessionHost: https://api.weixin.qq.com/sns/jscode2session


mall:
  swagger:
    enabled: true
    title: 用户中心
    description: 用户中心接口文档
    version: 1.0
    base-package: com.mallplus.user.controller
  cache-manager:
    configs:
      - key: menu
        second: 600
      - key: user
        second: 1800

