spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mallcloud?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.moke.common.model
  global-config:
    db-config:
      id-type: ID_WORKER_STR

mall:
  swagger:
    enabled: true
    title: 用户中心
    description: 用户中心接口文档
    version: 1.0
    base-package: com.moke.user.controller
  cache-manager:
    configs:
      - key: menu
        second: 600
      - key: user
        second: 1800
aliyun:
    oss:
        accessKeyId: 5Jii89BFukxmun5j
        accessKeySecret: JvE9FcILlHu5gClmAJr89ZkEv00l9s
        bucketName: yjlive160322
        callback: http://localhost:8080/aliyun/oss/callback
        dir:
            prefix: mall/images/
        endpoint: oss-cn-beijing.aliyuncs.com
        maxSize: 10
        policy:
            expire: 300
